version: "3.8"

services:
  db:
    image: "transaction:0.0.1"
    build:
      dockerfile: Dockerfile-mysql
    container_name: "transaction-db"
    environment:
      MYSQL_DATABASE: 'transaction'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
      - transaction-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  api:
    image: "transaction-tool-api:0.0.1"
    build:
      dockerfile: Dockerfile
    container_name: "transaction-tool-api"
    environment:
      LOCAL_ENV: "docker"
    ports:
      - "8080:8080"
    networks:
      - transaction-net
    depends_on:
      db:
        condition: service_healthy

    restart: always
networks:
  transaction-net:
    driver: bridge
